baseURL: https://example.com
languageCode: en
DefaultContentLanguage: en
title: R-gators
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: R-gators
  customCss: []
  customJs: []
  description: Gator. UF 🧡💙. Speaks R. 📍 Gainesville, Florida
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/UF-R.png
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://de.linkedin.com/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/lxndrblz/anatole/
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/
    - icon: fas fa-at
      title: e-mail
      url: mailto:mail@example.com
  title: R-gators
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: posts
      name: Posts
      url: /post/
      weight: 300
    - identifier: about
      name: About
      url: /about/
      weight: 200
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 400
